name: GitHub Actions - Terraform Controller
on:

####----------------------------------------------------------------------------
  workflow_dispatch:
    name: Manual Deployment
    description: 'Triggering Manual Deployment'
    inputs:
      accesskey:
        description: 'Target Access Key-ID'
        required: false
        default: ''
      account:
        description: 'Target AWS Account'
        required: false
        default: ''
      destroy-terraform:
        description: 'Terraform Destroy Request'
        required: false
        default: true
      keypair-name:
        description: 'Private Key-Pair Name'
        required: false
        default: ''
      keypair-secret:
        description: 'Private Key-Pair Secret'
        required: false
        default: ''
      region:
        description: 'Target AWS Region'
        required: false
        default: ''
      secretkey:
        description: 'Target Secret Access-Key'
        required: false
        default: ''
      workspace:
        description: 'Terraform Workspace'
        required: false
        default: 'dev'
      terraform-version:
        description: 'Terraform CLI Version (latest)'
        required: false
        default: '1.0.11'
      ####----------------------------------------------------------------------
      # logLevel:
      #   description: 'Log level'
      #   required: true
      #   default: 'warning'
      # tags:
      #   description: 'Terraform Controller'
####----------------------------------------------------------------------------
  push:
    branches: [ master ]
    paths:
      - action.yaml
####----------------------------------------------------------------------------
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
  AWS_DEFAULT_PROFILE: default  ## ${{ secrets.AWS_DEFAULT_PROFILE }}
  AWS_DEFAULT_REGION: us-east-1  ## ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ## Terraform Operations: Deploy, Destroy
  BACKUP_TERRAFORM: ${{ secrets.BACKUP_TERRAFORM }}
  DEPLOY_TERRAFORM: ${{ secrets.DEPLOY_TERRAFORM }}
  DESTROY_TERRAFORM: ${{ secrets.DESTROY_TERRAFORM }}
  ## DEVOPS_ASSUMEROLE_POLICY
  ## DEVOPS_BOUNDARIES_POLICY
  ## DEVOPS_ACCESS_POLICY
  DEVOPS_ACCESS_ROLE: ${{ secrets.DEVOPS_ACCESS_ROLE }}
  DEVOPS_ACCOUNT_NAME: devops  ## ${{ secrets.DEVOPS_ACCOUNT_NAME }}
  DYNAMODB_DEFAULT_REGION: us-east-1  ## ${{ secrets.DYNAMODB_DEFAULT_REGION }}
  ## INSPECT_DEPLOYMENT
  PRIVATE_KEYPAIR_FILE: .ssh/id_rsa  ## ${{ secrets.PRIVATE_KEYPAIR_FILE }}
  PRIVATE_KEYPAIR_NAME: devops  ## ${{ secrets.PRIVATE_KEYPAIR_NAME }}
  PRIVATE_KEYPAIR_SECRET: ${{ secrets.PRIVATE_KEYPAIR_SECRET }}
  PROVISION_TERRAFORM: ${{ secrets.PROVISION_TERRAFORM }}
  S3BUCKET_CONTAINER: pipelines
  S3BUCKET_DEFAULT_REGION: us-east-1  ## ${{ secrets.S3BUCKET_DEFAULT_REGION }}
  ## TERRAFORM_VERSION
  TARGET_WORKSPACE: dev  ## ${{ secrets.TARGET_WORKSPACE }}
  ## UPDATE_PYTHON_LATEST
  ## UPDATE_SYSTEM_LATEST
  ##
  terraform_input_params: ''
####----------------------------------------------------------------------------
jobs:
  terraform-controller:
    runs-on: ubuntu-latest
    steps:
####----------------------------------------------------------------------------
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## Environment Variables
      - name: Environment Variables
        id: environment-variables
        run: |
          ####------------------------------------------------------------------
          ## Parsing GitHub Action - Workflow dispatch (limited to 10 input-params)
          echo -e "Processing File|Input-based Parameters ... [ 1-10 ]\n" ;
          ####------------------------------------------------------------------
          echo "TARGET_WORKSPACE=$(
              cat ${{ github.workspace }}/workspace \
              | grep -vxE '[[:blank:]]*([#;].*)?' \
              | tr -d '[:space:]'
            )" >> ${GITHUB_ENV} ;
          ####------------------------------------------------------------------
          echo "SESSION_TIMESTAMP=$(date +"%y%m%d%H%M%S")" >> ${GITHUB_ENV} ;
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ${GITHUB_ENV} ;
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ${GITHUB_ENV} ;
          ####------------------------------------------------------------------
          custom_workspace="${{ github.event.inputs.workspace }}" ;
          if [[ (${#custom_workspace} -gt 0) && (${custom_workspace} != '') ]]; then
            echo -e "       Target Workspace [input-based]: '${custom_workspace}'" ;
            echo "TARGET_WORKSPACE=${custom_workspace}" >> ${GITHUB_ENV} ;
          fi ;
          ####------------------------------------------------------------------
          cloud_region="${{ github.event.inputs.region }}" ;
          if [[ (${#cloud_region} -gt 0 ) && (${cloud_region} != '') ]]; then
            echo -e "    Target Cloud Region [input-based]: '${cloud_region}'" ;
            echo "AWS_DEFAULT_REGION=${cloud_region}" >> ${GITHUB_ENV} ;
          fi ;
          ####------------------------------------------------------------------
          cloud_account="${{ github.event.inputs.account }}" ;
          if [[ (${#cloud_account} -gt 0 ) && (${cloud_account} != '') ]]; then
            echo -e "   Target Cloud Account [input-based]: '${cloud_account}'" ;
            echo "AWS_DEFAULT_ACCOUNT=${cloud_account}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          access_keyid="${{ github.event.inputs.accesskey }}" ;
          if [[ (${#access_keyid} -gt 0 ) && (${access_keyid} != '') ]]; then
            echo -e "   Target Access Key-ID [input-based]: '${access_keyid}'" ;
            echo "AWS_ACCESS_KEY_ID=${access_keyid}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          secret_keyid="${{ github.event.inputs.secretkey }}" ;
          if [[ (${#secret_keyid} -gt 0 ) && (${secret_keyid} != '') ]]; then
            echo -e "   Target Secret Key-ID [input-based]: '${secret_keyid}'" ;
            echo "AWS_SECRET_ACCESS_KEY=${secret_keyid}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          keypair_name="${{ github.event.inputs.keypair-name }}" ;
          if [[ (${#keypair_name} -gt 0 ) && (${keypair_name} != '') ]]; then
            echo -e "  Private Key-Pair Name [input-based]: '${keypair_name}'" ;
            echo "PRIVATE_KEYPAIR_NAME=${keypair_name}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          keypair_secret="${{ github.event.inputs.keypair-secret }}" ;
          if [[ (${#keypair_secret} -gt 0 ) && (${keypair_secret} != '') ]]; then
            private_keypair_secret="$(echo -e "${keypair_secret}" | sed -e "s|;$||" | tr ';' '\n')";
            echo -e "Private Key-Pair Secret [input-based]: \n'***'" ;
            echo "PRIVATE_KEYPAIR_SECRET=${private_keypair_secret}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          terraform_version="${{ github.event.inputs.terraform-version }}" ;
          if [[ (${#terraform_version} -gt 0 ) && (${terraform_version} != true) ]]; then
            echo -e "       Terraform Version [iput-based]: '${terraform_version}'" ;
            echo "TERRAFORM_VERSION=${terraform_version}" >> ${GITHUB_ENV} ;
          fi;
          ####------------------------------------------------------------------
          destroy_terraform="${{ github.event.inputs.destroy-terraform }}" ;
          if [[ (${#destroy_terraform} -gt 0 ) && (${destroy_terraform} != true) ]]; then
            echo -e "      Destroy Terraform [input-based]: '${destroy_terraform}'" ;
            echo "DESTROY_TERRAFORM=${destroy_terraform}" >> ${GITHUB_ENV} ;
          fi;
####----------------------------------------------------------------------------
      ## System Requirements
      - name: System Requirements
        uses: emvaldes/system-requirements@master
        id: system-requirements
        with:
          install-awscli-tool: true
          install-custom-tools: 'netcat'
          install-default-tools: true
          install-terraform-cli: latest
          target-terraform-version: ${TERRAFORM_VERSION}
          update-operating-system: ${UPDATE_SYSTEM_LATEST}
          update-python-version: ${UPDATE_PYTHON_LATEST}
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Installed Packages
      - name: Installed Packages
        id: installed-packages
        shell: bash
        run: |
          jq --version 2>/dev/null ;
          tree --version 2>/dev/null ;
          python --version 2>/dev/null ;
          aws --version 2>/dev/null ;
          terraform --version 2>/dev/null ;
####----------------------------------------------------------------------------
      ## Terraform Parameters
      - name: Terraform Parameters
        id: terraform-parameters
        shell: bash
        run: |
          remote_origin="$(git config --get remote.origin.url)" ;
          route53_record="${remote_origin##*\/}" ;
          oIFS="${IFS}" ; IFS=$'\n' ;
          declare -a custom_params=(
              custom_timestamp="${SESSION_TIMESTAMP}"
              custom_engineer='Eduardo Valdes'
              custom_contact='emvaldes@hotmail.com'
              custom_listset='["ami-abc123","ami-def456"]'
              custom_mapset='{"us-east-1":"ami-abc123","us-east-2":"ami-def456"}'
              route53_record="${SESSION_TIMESTAMP}.${route53_record}"
            ) ;
          ## echo -e "\nListing Encoding entries: ..." ;
          ## for xitem in ${custom_params[@]}; do
          ##   encrypted=$(echo -en ${xitem} | base64 -w0 | tr -d '\n\r') ;
          ##   decrypted=$(echo -en "${encrypted}" | base64 --decode) ;
          ##   echo -e "${encrypted} -> ${decrypted}" ;
          ## done ;
          echo "terraform_input_params=$(
              for xitem in ${custom_params[@]}; do
                echo -en "`echo -en ${xitem} | base64 -w0 | tr -d '\n\r'`_" ;
              done | sed -e 's|\(.*\)\(\_\)$|\1|' ;
            )" >> ${GITHUB_ENV} ;
          IFS="${oIFS}" ;
          echo "terraform_input_tfvars=configs/${TARGET_WORKSPACE}-configs.tfvars" >> ${GITHUB_ENV} ;
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Requesting Credentials
      - name: Requesting Credentials
        uses: emvaldes/generate-credentials@master
        id: request-credentials
        with:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-default-account: ${AWS_DEFAULT_ACCOUNT}
          aws-default-profile: ${AWS_DEFAULT_PROFILE}
          aws-default-region: ${AWS_DEFAULT_REGION}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          devops-access-role: ${DEVOPS_ACCESS_ROLE}
          devops-account-name: ${DEVOPS_ACCOUNT_NAME}
          session-timestamp: "DevOpsPipeline--${SESSION_TIMESTAMP}"
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Provisioning Access
      - name: Provisioning Access
        uses: emvaldes/configure-access@master
        id: provision-access
        with:
          private-keypair-file: ${PRIVATE_KEYPAIR_FILE}
          private-keypair-secret: "${PRIVATE_KEYPAIR_SECRET}"
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Provision Terraform
      - name: Provision Terraform
        uses: ./
        id: provision-terraform
        with:
          provision-terraform: ${PROVISION_TERRAFORM}
          terraform-input-params: "${terraform_input_params}"
          terraform-input-tfvars: "${terraform_input_tfvars}"
## Terraform Log-levels: TRACE, DEBUG, INFO, WARN or ERROR
          terraform-loglevel: false
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Deploy Terraform
      - name: Deploy Terraform
        uses: ./
        id: deploy-terraform
        with:
          deploy-terraform: ${DEPLOY_TERRAFORM}
## Terraform Log-levels: TRACE, DEBUG, INFO, WARN or ERROR
          terraform-loglevel: false
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Backup Terraform
      - name: Backup Terraform
        uses: emvaldes/provision-terraform@master
        id: backup-terraform
        with:
          backup-terraform: ${BACKUP_TERRAFORM}
        continue-on-error: false
####----------------------------------------------------------------------------
      ## Destroy Terraform
      - name: Destroy Terraform
        uses: ./
        id: destroy-terraform
        with:
          destroy-terraform: ${DESTROY_TERRAFORM}
## Terraform Log-levels: TRACE, DEBUG, INFO, WARN or ERROR
          terraform-loglevel: false
        continue-on-error: false
###----------------------------------------------------------------------------
